ServerRoot "/usr/local/apache2"
Listen 8080

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule headers_module modules/mod_headers.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule status_module modules/mod_status.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule env_module modules/mod_env.so

User daemon
Group daemon

ServerAdmin admin@localhost
ServerName localhost

ErrorLog /proc/self/fd/2
LogLevel warn
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
CustomLog /proc/self/fd/1 combined

<Directory />
    Options None
    AllowOverride None
    Require all denied
</Directory>

# Prometheus
<Location "/server-status">
    SetHandler server-status
    Require ip 172.0.0.0/8
</Location>

# Подключение vhost
Include conf/extra/vhost.conf
